name = "astro-v6-blog"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat", "no_handle_cross_request_promise_resolution"]

[assets]
directory = "./dist/client"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"

[observability]
enabled = true
